#!/usr/bin/env python3
"""Build a zip bundle of submission-facing artifacts."""

from __future__ import annotations

import argparse
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


def artifact_list() -> list[str]:
    return [
        "README.md",
        "Makefile",
        "run.sh",
        "docs/claim_boundary.md",
        "docs/proof_roadmap.md",
        "docs/assumption_to_evidence_map.md",
        "docs/reviewer_checklist.md",
        "docs/submission_guide.md",
        "docs/paper_claim_text.tex",
        "docs/formal_figures.tex",
        "docs/verification_tables.tex",
        "docs/results/release_status_latest.md",
        "docs/results/submission_rc_latest.md",
        "docs/results/submission_ready_latest.md",
        "docs/results/submission_artifact_manifest_latest.md",
        "docs/results/strong_claim_bundle_latest.md",
        "docs/results/fastlane_release_latest.md",
        "docs/results/proof_snapshot_latest.md",
        "docs/results/proof_blockers_latest.md",
        "docs/results/concrete_tlaps_probe_latest.md",
        "docs/results/safety_transfer_closure_attempt_latest.md",
        "docs/results/safety_transfer_failure_taxonomy_latest.md",
        "docs/results/safety_transfer_closure_trend_latest.md",
        "docs/results/safety_transfer_goalpack_latest.md",
        "docs/results/wrapper_projection_latest.md",
        "docs/results/mv5_suite_latest.md",
        "docs/results/scale_n7_attack_latest.md",
        "docs/results/scale_n7lite_suite_latest.md",
        "docs/results/scale_n7lite_full_suite_latest.md",
        "AdaptiveBFT_MainFlow.pdf",
        "AdaptiveBFT_Types.pdf",
        "modules/AVC_RVS.pdf",
        "modules/APS_Mempool.pdf",
        "AdaptiveBFT_Properties.pdf",
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    root = args.root.resolve()
    out = args.out.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    added = 0
    skipped = 0
    with ZipFile(out, "w", compression=ZIP_DEFLATED) as zf:
        for rel in artifact_list():
            src = root / rel
            if src.exists() and src.is_file():
                zf.write(src, arcname=rel)
                added += 1
            else:
                skipped += 1
        manifest = (
            "Submission bundle generated by scripts/build_submission_bundle.py\n"
            f"added={added}\n"
            f"skipped={skipped}\n"
        )
        zf.writestr("docs/results/submission_bundle_meta.txt", manifest)

    print(f"bundle: {out}")
    print(f"added: {added}")
    print(f"skipped: {skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
